# -*- coding: utf-8 -*-
#
# STSCI documentation build configuration file, created by
# sphinx-quickstart on Thu Oct 22 17:25:41 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import datetime
import json
import os
import sys
from lcviz import __version__

try:
    from sphinx_astropy.conf.v1 import *  # noqa
    from sphinx_astropy.conf.v2 import *  # noqa
except ImportError:
    print('ERROR: the documentation requires the sphinx-astropy package to be installed')
    sys.exit(1)

# -- General configuration ------------------------------------------------

# Configuration for intersphinx
intersphinx_mapping = {
    'jdaviz': ('https://jdaviz.readthedocs.io/en/latest/', None),
#     'python': ('https://docs.python.org/3/',
#                (None, 'http://data.astropy.org/intersphinx/python3.inv')),
#     'numpy': ('https://numpy.org/doc/stable/',
#               (None, 'http://data.astropy.org/intersphinx/numpy.inv')),
#     'scipy': ('https://docs.scipy.org/doc/scipy/reference/',
#               (None, 'http://data.astropy.org/intersphinx/scipy.inv')),
#     'matplotlib': ('https://matplotlib.org/',
#                    (None, 'http://data.astropy.org/intersphinx/matplotlib.inv')),  # noqa
#     'astropy': ('https://docs.astropy.org/en/stable/', None)
    }

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx_automodapi.automodapi',
    'sphinx.ext.mathjax',
    'sphinx_design',
    'sphinx_togglebutton',
    'docs_wireframe_demo',
    'jdaviz.ext.wireframe']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project
project = "lcviz"
author = "JDADF Developers"
year = datetime.datetime.now().year
copyright = f'{year}, {author}'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# build documents.
#
# The full version, including alpha/beta/rc tags.
release = __version__
dev = "dev" in release
# The short X.Y version.
version = '.'.join(release.split('.')[:2])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

suppress_warnings = ['intersphinx.fetch_inventory']

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = 'obj'

# Don't show summaries of the members in each class along with the
# class' docstring
numpydoc_show_class_members = False

autosummary_generate = True

automodapi_toctreedirnm = 'api'

# Class documentation should contain *both* the class docstring and
# the __init__ docstring
autoclass_content = "both"

# Render inheritance diagrams in SVG
graphviz_output_format = "svg"

graphviz_dot_args = [
    '-Nfontsize=10',
    '-Nfontname=Helvetica Neue, Helvetica, Arial, sans-serif',
    '-Efontsize=10',
    '-Efontname=Helvetica Neue, Helvetica, Arial, sans-serif',
    '-Gfontsize=10',
    '-Gfontname=Helvetica Neue, Helvetica, Arial, sans-serif'
]

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# A NOTE ON HTML THEMES
# The global astropy configuration uses a custom theme, 'bootstrap-astropy',
# which is installed along with astropy. A different theme can be used or
# the options for this theme can be modified by overriding some of the
# variables set in the global configuration. The variables set in the
# global configuration are listed below, commented out.

html_css_files = ["lcviz-wireframe.css"]
html_static_path = ['_static']
html_copy_source = False

html_theme_options.update(  # noqa: F405
    {
        "github_url": "https://github.com/spacetelescope/lcviz",
        "use_edit_page_button": True,
    }
)

html_context = {
    "default_mode": "light",
    "to_be_indexed": ["stable", "latest"],
    "is_development": dev,
    "github_user": "spacetelescope",
    "github_repo": "lcviz",
    "github_version": "main",
    "doc_path": "docs",
}

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = 'sphinx_rtd_theme'

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'logos/lcviz.svg'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'logos/lcviz.ico'

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {'**': ['globaltoc.html', 'relations.html', 'searchbox.html']}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = f'{project}doc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '14pt',
    # Additional stuff for the LaTeX preamble.
    'preamble': r'''\usepackage{enumitem} \setlistdepth{99}'''
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', f'{project}.tex', f'{project} Documentation',
   f'{project}', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
latex_show_urls = 'True'

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = True

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', f'{project}', f'{project} Documentation',
     [f'{project}'], 1)
]

# If true, show URL addresses after external links.
man_show_urls = True

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', f'{project}', f'{project} Documentation',
   f'{author}', f'{project}', f'{project}',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
texinfo_show_urls = 'inline'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = f'{project}'
epub_author = f'{author}'
epub_publisher = f'{author}'
epub_copyright = f'{year} {author}'

# The basename for the epub file. It defaults to the project name.
# epub_basename = u'wfc3tools'

# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and
# epub output is usually not wise. This defaults to 'epub', a theme designed
# to save visual space.
epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or en if the language is not set.
# epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
# epub_identifier = ''

# A unique identification for the text.
# epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
# epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
# epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
# epub_tocdepth = 3

# Allow duplicate toc entries.
# epub_tocdup = True

# Choose between 'default' and 'includehidden'.
# epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
# epub_fix_images = False

# Scale large images.
# epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# epub_show_urls = 'inline'

# If false, no index is generated.
# epub_use_index = True


# ---------------------------------------------------------------------------
# Landing page helpers and directive
# ---------------------------------------------------------------------------

def scan_directory_for_links(base_path, directory):
    """Scan a docs subdirectory and return a list of link dicts for the grid."""
    dir_path = os.path.join(base_path, directory)
    if not os.path.isdir(dir_path):
        return []

    links = [{'text': 'Overview', 'href': os.path.join(directory, 'index')}]

    acronyms = {'api': 'API', 'url': 'URL', 'tpf': 'TPF'}

    for filename in sorted(os.listdir(dir_path)):
        if filename.endswith('.rst') and filename not in ('index.rst', 'extensions.rst'):
            name = filename[:-4].replace('_', ' ').title()
            name_words = name.split()
            for i, word in enumerate(name_words):
                if word.lower() in acronyms:
                    name_words[i] = acronyms[word.lower()]
            name = ' '.join(name_words)
            rel_path = os.path.join(directory, filename[:-4])
            links.append({'text': name, 'href': rel_path})

    return links


docs_dir = os.path.dirname(__file__)

grid_items_data = [
    {
        'title': 'Data Loaders',
        'description': 'Import light curves and target pixel files into jdaviz',
        'icon': 'mdi-plus-box',
        'grid_id': 'grid-loaders',
        'links': [
            {'text': 'Overview', 'href': 'loaders/index'},
            {'text': 'Light Curve', 'href': 'loaders/light_curve'},
            {'text': 'Target Pixel File', 'href': 'loaders/tpf'},
        ],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/loaders/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Viewers',
        'description': 'Visualize light curves in time and phase space',
        'icon': 'mdi-plus-box',
        'grid_id': 'grid-viewers',
        'links': [
            {'text': 'Overview', 'href': 'viewers/index'},
            {'text': 'Flux vs Time', 'href': 'viewers/flux_vs_time'},
            {'text': 'Flux vs Phase', 'href': 'viewers/flux_vs_phase'},
        ],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/viewers/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Data Analysis Plugins',
        'description': 'Analyze light curves and TPF data with lcviz-specific plugins',
        'icon': 'mdi-tune-variant',
        'grid_id': 'grid-plugins',
        'links': scan_directory_for_links(docs_dir, 'plugins'),
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/plugins/index.html',
        'has_toggle': True,
    },
    {
        'title': 'Subsets',
        'description': 'Select regions of interest in your data, synced across all viewers',
        'icon': 'mdi-tune-variant',
        'grid_id': 'grid-subsets',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/subsets/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Export',
        'description': 'Export generated data, selected subsets, and viewers',
        'icon': 'mdi-content-save',
        'grid_id': 'grid-export',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/export/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Flexible Settings & Options',
        'description': 'Choose how to visualize your data, including display units and plot options',
        'icon': 'mdi-tune-variant',
        'grid_id': 'grid-settings',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/settings/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Access to Data Info',
        'description': 'Interactive access to information about your data and generated results',
        'icon': 'mdi-tune-variant',
        'grid_id': 'grid-info',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/info/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Data Menu',
        'description': 'Control data and subset layer order and visibility for each viewer',
        'icon': 'mdi-plus-box',
        'grid_id': 'grid-data-menu',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/data_menu/index.html',
        'has_toggle': False,
    },
    {
        'title': 'Mouseover Information',
        'description': 'See information about the data directly below your cursor',
        'icon': 'mdi-plus-box',
        'grid_id': 'grid-mouseover',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/mouseover/index.html',
        'has_toggle': False,
    },
    {
        'title': 'API Access in Notebook',
        'description': 'Script advanced and reproducible workflows via Python API',
        'icon': 'mdi-tune-variant',
        'grid_id': 'grid-userapi',
        'links': [],
        'jdaviz_link': 'https://jdaviz.readthedocs.io/en/latest/userapi/index.html',
        'has_toggle': False,
    },
]

html_context['grid_items'] = grid_items_data
html_context['lcviz_version'] = version if dev else release


from docutils import nodes
from sphinx.util.docutils import SphinxDirective


class LcvizLandingPageDirective(SphinxDirective):
    """Render the lcviz landing page template."""

    def run(self):
        import jinja2

        template_dir = os.path.join(self.env.srcdir, '_templates')
        jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(template_dir)
        )

        def pathto(otheruri, resource=False):
            if resource:
                return otheruri
            if not otheruri.endswith('.html') and not otheruri.startswith('#'):
                otheruri = otheruri + '.html'
            return otheruri

        template = jinja_env.get_template('index.html')
        app_html_context = self.env.app.config.html_context

        context = {
            'grid_items': app_html_context.get('grid_items', []),
            'lcviz_version': app_html_context.get('lcviz_version', ''),
            'pathto': pathto,
        }
        html_content = template.render(context)
        raw_node = nodes.raw('', html_content, format='html')
        return [raw_node]


def _rst_filename_to_title(fn):
    """Convert an RST filename to a human-readable title."""
    name = fn[:-4]  # strip .rst
    name = name.replace('_', ' ')
    # Capitalize each word, preserve known acronyms
    acronyms = {'tpf': 'TPF', 'url': 'URL', 'api': 'API'}
    words = name.split()
    for i, w in enumerate(words):
        if w.lower() in acronyms:
            words[i] = acronyms[w.lower()]
        else:
            words[i] = w.title()
    return ' '.join(words)


def _generate_conf_settings_js(app):
    """Generate a JS file exposing build-time settings for the wireframe demo."""
    docs_dir = os.path.dirname(__file__)
    settings = {}

    settings['version'] = app.config.html_context.get('lcviz_version', '')

    # Scan loaders/ for RST files to populate format dropdown options
    loaders_dir = os.path.join(docs_dir, 'loaders')
    names = ['auto']
    if os.path.isdir(loaders_dir):
        for fn in sorted(os.listdir(loaders_dir)):
            if fn.endswith('.rst') and fn not in ('index.rst',):
                names.append(_rst_filename_to_title(fn))
    settings['loaderFormats'] = names

    static_dir = os.path.join(docs_dir, '_static')
    os.makedirs(static_dir, exist_ok=True)
    js_path = os.path.join(static_dir, 'jdaviz-conf-settings.js')
    with open(js_path, 'w') as f:
        f.write('// Auto-generated by conf.py — do not edit\n')
        f.write('window.__confSettings = %s;\n' % json.dumps(settings))


def setup(app):
    app.add_directive('lcvizlanding', LcvizLandingPageDirective)
    app.connect('builder-inited', _generate_conf_settings_js)
    app.add_js_file('jdaviz-conf-settings.js')
