# GitHub Actions workflow that runs on a cron schedule.
name: Cron Scheduled CI Tests

on:
  workflow_dispatch:
  schedule:
    # run at 9am UTC on Mondays
    - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  # The linkcheck job tests that the links in the docs point to real places
  # The if statement is to prevent cron from running on forks.
  linkcheck:
    runs-on: ubuntu-latest
    if: github.repository == 'spacetelescope/lcviz'
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
    - name: Set up Python to build docs with sphinx
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: '3.10'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Check links in docs using tox
      run: tox -e linkcheck

  ci_cron_tests:
    name: Python 3.10 with latest dev versions of key dependencies
    runs-on: ubuntu-latest
    if: github.repository == 'spacetelescope/lcviz'
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      with:
        fetch-depth: 0
    - name: Set up python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: '3.10'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: tox -e py310-test-devdeps
